[DEFAULT]
default_key = "sk-ELU04Pbyk63Yem8YD074D79cFd4b446dBe8eAf3fF4C7E6A9"
default_base = "https://api.gpt.ge/v1"
default_model = "gpt-4o-mini"
default_temperature = 0.5

[WHISPER]
openai_whisper_api = false
faster_whisper_model_default = "tiny"
faster_whisper_model_local = true
faster_whisper_model_local_path = "F:/new/model/tiny"
gpu = false
vad = false
lang = "自动识别"

[MORE]
min_vad = 500
beam_size = 5
whisper_prompt = "Please break sentences correctly and retain punctuation."
temperature = 0.5
crf = 23
quality = "medium"
ffmpeg = "libx264"
log = "error"
